const $=s=>document.querySelector(s),S={q:[],sub:'All'};function p(t){let y,g,o=[];for(let b of t.replace(/\r/g,'').split(/\n\s*\n/)){let m=b.match(/^YEAR:\s*(\d{4})/m);if(m){y=+m[1];continue}m=b.match(/^\[([^|\]]+)\s*\|\s*Unit:\s*([^|\]]+)\s*\|\s*Topic:\s*([^\]]+)\]/m);if(m)g={subject:m[1].trim(),unit:m[2].trim(),topic:m[3].trim()};let q=b.match(/Q\.(\d+)\.\s*([\s\S]*?)(?=\nA\.\s)/),a=[...b.matchAll(/^([A-E])\.\s*(.*)$/gm)];if(q&&g&&y&&a.length>1)o.push({year:y,...g,stem:q[2].trim(),a})}return o}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
let answers={};try{answers=JSON.parse(localStorage.getItem('myelin-answers')||'{}')}catch{}
function key(x){return x.year+':'+x.stem}
function show(q,t,k){
$('#question-kicker').textContent=k;
$('#question-title').textContent=t;
function progress(){$('#question-count').textContent=q.filter(x=>answers[key(x)]).length+' / '+q.length+' attempted · Answer key not supplied; scoring unavailable. Tags are supplied, not independently verified.'}
progress();
$('#question-list').innerHTML=q.map((x,i)=>'<article class="question"><div class="question-meta">'+esc(x.year+' · '+x.subject+' · '+x.unit+' · '+x.topic)+'</div><div class="question-stem">'+(i+1)+'. '+esc(x.stem)+'</div><div class="options" role="group" aria-label="Answers for question '+(i+1)+'">'+x.a.map(a=>'<button type="button" class="option" style="text-align:left;cursor:pointer" data-q="'+i+'" data-answer="'+a[1]+'" aria-pressed="'+(answers[key(x)]===a[1])+'"><b>'+a[1]+'.</b>'+esc(a[2])+'</button>').join('')+'</div></article>').join('');
function paint(){document.querySelectorAll('[data-answer]').forEach(b=>{const selected=answers[key(q[Number(b.dataset.q)])]===b.dataset.answer;b.setAttribute('aria-pressed',String(selected));b.style.background=selected?'#dbeafe':'#f8fafc';b.style.borderColor=selected?'#2563eb':'#e5eaf1'})}
document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{answers[key(q[Number(b.dataset.q)])]=b.dataset.answer;try{localStorage.setItem('myelin-answers',JSON.stringify(answers))}catch{}paint();progress()});paint();
$('#questions').hidden=false;$('#questions').scrollIntoView({behavior:'smooth'})
}
function run(){let c={};S.q.forEach(x=>c[x.year]=(c[x.year]||0)+1);$('#year-grid').innerHTML=Object.keys(c).map(y=>'<button class="year-card" data-y="'+y+'"><strong>'+y+'</strong><span>'+c[y]+' imported MCQs</span><span class="badge">OPEN PAPER →</span></button>').join('');document.querySelectorAll('[data-y]').forEach(b=>b.onclick=()=>show(S.q.filter(x=>x.year==b.dataset.y),'UHS MDCAT '+b.dataset.y,'YEAR-WISE PAPER'));let d={};S.q.filter(x=>S.sub==='All'||x.subject===S.sub).forEach(x=>(d[x.unit]??=[]).push(x));$('#unit-grid').innerHTML=Object.entries(d).map(([u,q],i)=>'<button class="unit-card" data-u="'+i+'"><strong>'+u+'</strong><span>'+q.length+' imported MCQs</span><span class="badge">PRACTISE UNIT →</span></button>').join('');document.querySelectorAll('[data-u]').forEach(b=>{let e=Object.entries(d)[b.dataset.u];b.onclick=()=>show(e[1],e[0],S.sub+' · UNIT PRACTICE')});let z=['All',...new Set(S.q.map(x=>x.subject))];$('#subject-tabs').innerHTML=z.map(x=>'<button class="tab '+(x===S.sub?'active':'')+'" data-s="'+x+'">'+x+'</button>').join('');document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{S.sub=b.dataset.s;run()})}fetch('data/years/2008.txt').then(r=>{if(!r.ok)throw new Error('Paper could not be loaded');return r.text()}).then(t=>{S.q=p(t);let ys=new Set(S.q.map(x=>x.year));$('#stats').innerHTML='<div class="stat"><strong>'+S.q.length+'</strong><small>IMPORTED MCQs</small></div><div class="stat"><strong>'+ys.size+'</strong><small>AVAILABLE YEARS</small></div><div class="stat"><strong>'+new Set(S.q.map(x=>x.unit)).size+'</strong><small>PMDC UNITS</small></div>';run()}).catch(e=>{$('#stats').textContent='Unable to load the paper. Please refresh.';console.error(e)});$('#back-button').onclick=()=>$('#questions').hidden=true;$('#copyright-year').textContent=new Date().getFullYear();
$('#year-search').oninput=e=>document.querySelectorAll('[data-y]').forEach(b=>b.hidden=!b.dataset.y.includes(e.target.value.trim()));
